# Generated by Django 4.2.13 on 2024-12-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_content_de_post_content_en_post_content_fa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
